### ISSUE TITLE
尚学堂的项目，而且工作流部分也没写，已经看到最少20人发布这个项目了

### ISSUE THREAD

**Issue by CihaoChung** [yeqifu/warehouse#9]

**Comment by yeqifu** [comment]
你想说什么？

**Comment by Wadewhy** [comment]
> 你想说什么？

nothing，只是太多人发布这个了，还全写作者是自己，觉得很奇怪

**Comment by yeqifu** [comment]
老子一行一行代码跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。

**Comment by Wadewhy** [comment]
> 老子一行一行跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。

戳到痛处了？？？

**Comment by Wadewhy** [comment]
> > 老子一行一行跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。
> 
> 戳到痛处了？？？

销售退货不就是按照其他的controller差不多？？如果你集成了工作流我就不说什么。主要是和其他人代码相似度达到90%，我觉得很可笑而已

**Comment by Wadewhy** [comment]
> 老子一行一行跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。

我也很后悔看到，早知道不点开了，污染眼睛

**Comment by Wadewhy** [comment]
> 老子一行一行跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。

还有其他问题？？？没有的话就不用回了

**Comment by Wadewhy** [comment]
> 老子一行一行代码跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。

那个老师没有讲集成工作流，然后你也不写。只能写他讲了的，不用我多说什么吧。自己想想

**Comment by yeqifu** [comment]
你知道雷哥的代码有不少BUG么，它写的代码将商品全部删除，商品进货和商品退货就空指针，我是对这做了优化的，如果将商品删除时，需要同步删除商品进货和商品退货以及商品销售和商品销售退货。删除用户的时候，我也进行了优化，如果该用户是其他的用户的直属领导就无法删除，如果要删除必须得先修改该用户所有的下属的直属领导，后台首页的公告我也做了优化，如果后台首页的公告数量少了5条，按雷哥的写法是出不来的，他当时是写死的。我做了这么多的修改，你又知道什么？

**Comment by Wadewhy** [comment]
> 你知道雷哥的代码有不少BUG么，它写的代码将商品全部删除，商品进货和商品退货就空指针，我是对这做了优化的，如果将商品删除时，需要同步删除商品进货和商品退货以及商品销售和商品销售退货。删除用户的时候，我也进行了优化，如果该用户是其他的用户的直属领导就无法删除，如果要删除必须得先修改该用户所有的下属的直属领导，后台首页的公告我也做了优化，如果后台首页的公告数量少了5条，按雷哥的写法是出不来的，他当时是写死的。我做了这么多的修改，你又知道什么？

就这？？我可以说你离开他的代码，要你写集成非layui框架的dtree树目录，你都写不来。

**Comment by yeqifu** [comment]
我写不写的来和你有没关系，不需要你阴阳怪气。

**Comment by yeqifu** [comment]
以后有时间了，我就把工作流的请假审批给写了，你别急

**Comment by Wadewhy** [comment]
> 以后有时间了，我就把工作流的请假审批给写了，你别急

Waiting for you

**Comment by wonderfulMorty** [comment]
> > 老子一行一行代码跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。
> 
> 那个老师没有讲集成工作流，然后你也不写。只能写他讲了的，不用我多说什么吧。自己想想

雷老师Naga加了工作流的是要收费的，不加工作流是免费的，我看你就是想白嫖。

**Comment by Wadewhy** [comment]
看的懂中文吗？我的意思是说那个老师没讲他就没写，表达的是他只会安装老师讲的来。还什么收费，我不知道收不收费。你戏真多，笑死我了，你这理解能力别回复了。-------- 原始邮件 --------发件人： Morty <notifications@github.com>日期： 2020年4月13日周一 下午5:56收件人： yeqifu/warehouse <warehouse@noreply.github.com>抄送： wadewhy <wadewhy@yeah.net>, Author <author@noreply.github.com>主    题： Re: [yeqifu/warehouse] 尚学堂的项目，而且工作流部分也没写，已经看到最少20人发布这个项目了。。。。 (#9)


老子一行一行代码跟着雷老师敲的，然后把老师没写的商品销售和销售退货给写了，作者不写我自己，难不成写你，现在阴阳怪气的人真是多。给其他人一点IDEA写的代码的参考，就跟我是直接把人家的东西一点不落复制过来的样的，不想看就出门左拐。

那个老师没有讲集成工作流，然后你也不写。只能写他讲了的，不用我多说什么吧。自己想想

雷老师Naga加了工作流的是要收费的，不加工作流是免费的，我看你就是想白嫖。

**Comment by yeqifu** [comment]
是你把这个项目放到闲鱼上去卖的？

**Comment by Wadewhy** [comment]
？？？没有，我看到很多人发布，也有在网上卖的，大部分代码都是那个老师一样的，改都没改，然后刚刚那个兄弟说收费，属实给我整懵逼了



在 2020-04-13 18:23:01，"yeqifu" <notifications@github.com> 写道：

是你把这个项目放到闲鱼上去卖的？

**Comment by yeqifu** [comment]
你就别逼逼了，我是开源的，又没有收钱，工作流会补的，不知到你纠结这个干嘛，你觉得我技术不行那就不行，你都是对的。你厉害就自己去写工作流，别来我这吵了，谢谢。

**Comment by CihaoChung** [comment]
笑死，还开源，要开源也是那个老师开源，你属于二次修改，而且也没见你添加什么功能，还开源......技术行不行我不在乎，主要时拿别人的项目在网络上说自己的，原作者都不标出。谁在乎你的技术，只是看到写作者自己很搞笑，连原作者提都不提。

**Comment by CihaoChung** [comment]
> 你就别逼逼了，我是开源的，又没有收钱，工作流会补的，不知到你纠结这个干嘛，你觉得我技术不行那就不行，你都是对的。你厉害就自己去写工作流，别来我这吵了，谢谢。

笑死，还开源，要开源也是那个老师开源，你属于二次修改，而且也没见你添加什么功能，还开源......技术行不行我不在乎，主要时拿别人的项目在网络上说自己的，原作者都不标出。谁在乎你的技术，只是看到写作者自己很搞笑，连原作者提都不提。
